### ISSUE TITLE
Lab does not work

### ISSUE THREAD

**Issue by adybas** [learn-co-curriculum/active-record-practice-flatiron-bnb-lab#1]
1. Rails rake task included instead of sinatra task
2. Cannot get 'rake db:create_migrations' command to work in terminal

**Comment by maxwellbenton** [comment]
Hi @adybas,

Thank you for reporting this. Although this lab was originally built using Rails, we were able to add the sinatra/activerecord gem to this lab and have confirmed that `rake db:create_migration` is now available and functioning which should resolve this issue for future students.

Thanks for contributing!
