### ISSUE TITLE
Cannot get 'rake db:create_migrations' command to work in terminal

### ISSUE THREAD

**Issue by seanb113** [learn-co-curriculum/active-record-practice-flatiron-bnb-lab#3]
Cannot get 'rake db:create_migrations' command to work in terminal

**Comment by maxwellbenton** [comment]
Hi @seanb113,

Thank you for reporting this. We've added the sinatra/activerecord gem to this lab and confirmed that `rake db:create_migration` is now available and functioning.

Thanks for contributing!
